server:
  port: 8080

logging:
  level:
    com:
      study: DEBUG
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: security

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security_test1?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.study.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
