server:
  port: 8080
  servlet:
    context-path: /security

spring:
  application:
    name: security-test
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  datasource:
    url: jdbc:mysql://36.111.28.104:3306/user_db?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.study.entity
  # 配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0